core/urls.py
from django.urls import path, include

from .api import router
from .views import (EmployeeListView, EmployeeCreateView, EmployeeUpdateView, EmployeeDeleteView,
                    EmployeeDetailView, EnterpriseListView, EnterpriseCreateView, EnterpriseUpdateView,
                    EnterpriseDeleteView,
                    EnterpriseDetailView, SiteListView, SiteCreateView, SiteUpdateView, SiteDeleteView,
                    SiteDetailView, TagListView, TagCreateView, TagUpdateView, TagDeleteView,
                    TagDetailView, ZoneListView, ZoneCreateView, ZoneUpdateView, ZoneDeleteView,
                    ZoneDetailPlanningListView, ZoneDetailPlanningCreateView, ZoneDetailPlanningUpdateView,
                    ZoneDetailPlanningDeleteView, ZoneDetailPlanningDetailView, ZoneConfirmPlanningView,
                    ZoneReopenPlanningView)

urlpatterns = [
    path('api/', include(router.urls)),
    # Enterprise path
    path('enterprises', EnterpriseListView.as_view(), name='enterprise_list'),
    path('enterprises/create', EnterpriseCreateView.as_view(), name='enterprise_create'),
    path('enterprises/<int:pk>', EnterpriseDetailView.as_view(), name='enterprise_detail'),
    path('enterprises/<int:pk>/update', EnterpriseUpdateView.as_view(), name='enterprise_update'),
    path('enterprises/<int:pk>/delete', EnterpriseDeleteView.as_view(), name='enterprise_delete'),

    # Site path
    path('sites', SiteListView.as_view(), name='site_list'),
    path('sites/create', SiteCreateView.as_view(), name='site_create'),
    path('sites/<int:pk>', SiteDetailView.as_view(), name='site_detail'),
    path('sites/<int:pk>/update', SiteUpdateView.as_view(), name='site_update'),
    path('sites/<int:pk>/delete', SiteDeleteView.as_view(), name='site_delete'),

    # Zone path
    path('zones', ZoneListView.as_view(), name='zone_list'),
    path('zones/create', ZoneCreateView.as_view(), name='zone_create'),
    path('zones/<int:pk>/update', ZoneUpdateView.as_view(), name='zone_update'),
    path('zones/<int:pk>/delete', ZoneDeleteView.as_view(), name='zone_delete'),
    path('zones/<int:pk>/confirm', ZoneConfirmPlanningView.as_view(), name='zone_confirm'),
    path('zones/<int:pk>/reopen', ZoneReopenPlanningView.as_view(), name='zone_reopen'),

    # Zone Planning
    path('zones/<int:parent_pk>/<int:day_index>/plannings/', ZoneDetailPlanningListView.as_view(), name='zone_detail'),
    path('zones/<int:parent_pk>/<int:day_index>/plannings/create', ZoneDetailPlanningCreateView.as_view(), name='planning_create'),
    path('zones/<int:parent_pk>/<int:day_index>/plannings/<int:pk>', ZoneDetailPlanningDetailView.as_view(), name='planning_detail'),
    path('zones/<int:parent_pk>/<int:day_index>/plannings/<int:pk>/update', ZoneDetailPlanningUpdateView.as_view(), name='planning_update'),
    path('zones/<int:parent_pk>/<int:day_index>/plannings/<int:pk>/delete', ZoneDetailPlanningDeleteView.as_view(), name='planning_delete'),

    # Employee path
    path('employees', EmployeeListView.as_view(), name='employee_list'),
    path('employees/create', EmployeeCreateView.as_view(), name='employee_create'),
    path('employees/<int:pk>', EmployeeDetailView.as_view(), name='employee_detail'),
    path('employees/<int:pk>/update', EmployeeUpdateView.as_view(), name='employee_update'),
    path('employees/<int:pk>/delete', EmployeeDeleteView.as_view(), name='employee_delete'),

    # tag path
    path('tags', TagListView.as_view(), name='tag_list'),
    path('tags/create', TagCreateView.as_view(), name='tag_create'),
    path('tags/<int:pk>', TagDetailView.as_view(), name='tag_detail'),
    path('tags/<int:pk>/update', TagUpdateView.as_view(), name='tag_update'),
    path('tags/<int:pk>/delete', TagDeleteView.as_view(), name='tag_delete'),
]

secuGuard/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views


from core import urls as core_urls
from core.views import Home, AppLoginView, AppLogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('auth/', AppLoginView.as_view(), name='login'),
    path('api-token-auth/', views.obtain_auth_token),
    path('auth/logout/', AppLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('core/', include(core_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
import calendar

# Calendar settings
calendar.setfirstweekday(calendar.SUNDAY)
HOLIDAY_DAY_INDEX = 8
WEEK_DAYS_MAPPING = (
    (calendar.MONDAY, 'Lundi'),
    (calendar.TUESDAY, 'Mardi'),
    (calendar.WEDNESDAY, 'Mercredi'),
    (calendar.THURSDAY, 'Jeudi'),
    (calendar.FRIDAY, 'Vendredi'),
    (calendar.SATURDAY, 'Samedi'),
    (calendar.SUNDAY, 'Dimanche'),
    (HOLIDAY_DAY_INDEX, 'Jours fériés'))


class TimestampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='Créé')
    modified = models.DateTimeField(auto_now=True, verbose_name='Modifié')

    class Meta:
        abstract = True


class Enterprise(TimestampModel):
    designation = models.CharField(max_length=255, verbose_name='Nom de l\'entreprise')

    class Meta:
        verbose_name = 'Entreprise'

    def __str__(self):
        return self.designation


class Site(TimestampModel):
    designation = models.CharField(max_length=255, verbose_name='Nom du site')
    enterprise = models.ForeignKey(Enterprise, on_delete=models.CASCADE)

    def __str__(self):
        return self.designation + f" ({self.enterprise.designation})"


class Zone(TimestampModel):
    PLAN_STATES = (
        (1, 'Brouillon'),
        (2, 'Validé'),
    )
    designation = models.CharField(max_length=255, verbose_name='Nom de la zone')
    site = models.ForeignKey(Site, on_delete=models.CASCADE, verbose_name='Site')
    plan_state = models.IntegerField(choices=PLAN_STATES, default=PLAN_STATES[0][0], editable=False)

    def __str__(self):
        return self.designation + f" ({self.site.designation} - {self.site.enterprise.designation})"

    def validate_plan(self):
        self.plan_state = self.PLAN_STATES[1][0]
        self.save()

    def invalidate_plan(self):
        self.plan_state = self.PLAN_STATES[0][0]
        self.save()

    def create_planned_checkpoints(self):
        current_datetime = timezone.now()
        today = current_datetime.date()
        today_weekday_index = calendar.weekday(today.year, today.month, today.day)

        # Update check plan
        future_plans = PatrolLog.objects.filter(
            check_datetime__gte=current_datetime,
            tag__zone=self
        )
        future_plans.delete()

        related_tags = Tag.objects.filter(zone=self)  # Tags assigned to the current Zone
        zone_planning = Planning.objects.filter(zone=self)

        for plan in zone_planning:
            if plan.selected_day_index != HOLIDAY_DAY_INDEX:  # holidays index
                for tag in related_tags:
                    if today_weekday_index <= plan.selected_day_index:
                        check_date = today + datetime.timedelta(plan.selected_day_index - today_weekday_index)
                    else:
                        check_date = today + datetime.timedelta(plan.selected_day_index)
                    check_time = plan.patrol_check_time
                    check_datetime = datetime.datetime.combine(check_date, check_time)
                    PatrolLog.objects.create(
                        tag=tag,
                        check_tolerance=plan.tolerated_time,
                        check_datetime=check_datetime,
                        planning=plan
                    )
                    # todo if holidays ?

    def do_action(self, action, user):
        if action == 'confirm':
            self.create_planned_checkpoints()
            self.validate_plan()
        elif action == 'reopen':
            self.invalidate_plan()


class Employee(TimestampModel):
    designation = models.CharField(max_length=255, verbose_name='Nom de l\'employée')
    code_pin = models.CharField(max_length=6, verbose_name='Code PIN')
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    code_pin = models.CharField(max_length=255, verbose_name='Code PIN', null=True)

    class Meta:
        verbose_name = 'Employée'

    def __str__(self):
        return self.designation


class Tag(TimestampModel):
    zone = models.ForeignKey(Zone, on_delete=models.CASCADE, verbose_name='Zone')
    code_nfc = models.CharField(max_length=255, verbose_name='code NFC')
    designation = models.CharField(max_length=255, verbose_name='Nom du TAG')
    order = models.PositiveIntegerField(verbose_name='Ordre', blank=True, null=True)
    observation = models.CharField(max_length=255, verbose_name='Observation')

    class Meta:
        verbose_name = 'Tag'

    def __str__(self):
        return self.designation
    



class Holiday(TimestampModel):
    designation = models.CharField(max_length=100, verbose_name='Désignation')
    date = models.DateField(verbose_name='Date')



class Planning(TimestampModel):
    zone = models.ForeignKey(Zone, on_delete=models.CASCADE, verbose_name='Zone', editable=False)
    selected_day_index = models.IntegerField(choices=WEEK_DAYS_MAPPING, editable=False)
    patrol_check_time = models.TimeField(auto_now=False, auto_now_add=False,
                                         verbose_name='Heure de début de la tournée')
    tolerated_time = models.DurationField(verbose_name='Temps toléré')
    observation = models.TextField(verbose_name='Observation', blank=True, null=True)

    def __str__(self):
        return f"Check time : {self.patrol_check_time} (+{self.tolerated_time})"

    def save(self, *args, **kwargs):
        if self.zone.plan_state != 1:
            raise ValidationError('Vous ne pouvez pas modifier un planning valider !')
        else:
            super().save(args, kwargs)

class PatrolLog(TimestampModel):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, verbose_name='Tag')
    audio_path = models.CharField(max_length=255, verbose_name='Lien de la memo-vocale', blank=True, null=True)
    image_path = models.ImageField(null=True, blank=True, upload_to="images/")
    description_anomaly = models.TextField(verbose_name='Anomalie', blank=True, null=True)
    is_checked = models.BooleanField(verbose_name='tag visité', default=False)
    check_datetime = models.DateTimeField('Date / Heure prévue ')
    check_tolerance = models.DurationField('Tolérance')
    checked_datetime = models.DateTimeField(verbose_name='Date / Heure de passage', blank=True, null=True,
                                            editable=False)
    checked_by = models.ForeignKey(Employee, on_delete=models.PROTECT,
                                   verbose_name=('Controlé par'),
                                   null=True, blank=True, editable=False)
    planning = models.ForeignKey(Planning, on_delete=models.SET_NULL,null=True, verbose_name='Planning')

    class Meta:
        verbose_name = 'Journal des tournées'

    def __str__(self):
        return self.tag.designation

core/templates/core/zone/zone_confirm_delete.html
{% extends "base.html" %}
{%  load  static %}
{% block breadcrumbs %}
    <div class="w3-bar w3-dark-gray">
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'home' %}">Accueil</a></div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'zone_list' %}">Liste des Zones</a>
        </div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>

    </div>
{% endblock %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p class="w3-padding-top-24">Voulez-vous vraiment supprimer l' enregistrement <span>{{ object }}</span> ?
        </p>
        <input class="w3-button w3-theme-l1 w3-round" type="submit" value="Supprimer"/>
        <a class="w3-button w3-border w3-round" href="javascript:history.back()">Annuler</a>
    </form>
{% endblock %}

core/templates/core/zone/zone_confirm_planning.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumbs %}
    <div class="w3-bar w3-dark-gray">
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'home' %}">Accueil</a></div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'zone_list' %}">Liste des Zones</a>
        </div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>

    </div>
{% endblock %}
{% block content %}
    <form method="POST" action="{% url 'zone_confirm' pk=object.pk %}">
        {% csrf_token %}
        <p class="w3-padding-16 w3-padding-top-24 ">Voulez-vous vraiment <b>{{ action_name }}</b> le planning de la zone <b>{{ object }}</b> ?
        </p>
        <input class="w3-button w3-theme-l1 w3-round" type="submit" value="{{ action_name }}"/>
        <a class="w3-button w3-border w3-round" href="javascript:history.back()">Annuler</a>
    </form>
{% endblock %}

core/templates/core/zone/zone_detail.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumbs %}
    <div class="w3-bar w3-dark-gray">
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'home' %}">Accueil</a></div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'zone_list' %}">Liste des Zones</a>
        </div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>

    </div>
{% endblock %}
{% block content %}
    {% include 'core/zone/planning/parent_section.html' %}

    {#    Child object List#}
    <div class="w3-padding-32">
        {#    Tab bar#}
        {% include 'core/zone/planning/_days_tab_bar.html' %}
        <div class="w3-padding-16">
            <a class="w3-button w3-theme-l1 w3-round"
               href="{% url 'planning_create' parent_pk=parent_object.pk day_index=request.resolver_match.kwargs.day_index %}">
                <img src="{% static 'core/icons/plus_white_icon.png' %}" height="17">
                <span class="w3-margin-left">Ajouter</span>
            </a>
        </div>
        <table class="w3-table w3-white w3-bordered">
            <thead>
            <th>ID</th>
            <th>Ckeck Time</th>
            <th>Tolérance</th>
            <th>Actions</th>
            </thead>

            {% for obj in object_list %}
                <tr>
                    <td> {{ obj.id }}</td>
                    <td> {{ obj.patrol_check_time }}</td>
                    <td> {{ obj.tolerated_time }}</td>
                    <td>
                        <a class="w3-button w3-padding-small w3-round"
                           href="{% url 'planning_detail' parent_pk=parent_object.pk day_index=obj.selected_day_index pk=obj.pk %}">
                            {% include 'components/_view_icon.html' with height=19 %}
                        </a>
                        <a class="w3-button w3-padding-small w3-round"
                           href="{% url 'planning_update' parent_pk=parent_object.pk day_index=obj.selected_day_index pk=obj.pk %}">
                            {% include 'components/_modify_icon.html' with height=19 %}
                        </a>
                        <a class="w3-button w3-padding-small w3-round"
                           href="{% url 'planning_delete' parent_pk=parent_object.pk day_index=obj.selected_day_index pk=obj.pk %}">
                            {% include 'components/_delete_icon.html'  with height=19 %}</a>

                    </td>
                </tr>

            {% endfor %}
        </table>
    </div>
{% endblock %}

core/templates/core/zone/zone_form.html
{% extends "base.html" %}
{%  load  static %}
{% block breadcrumbs %}
    <div class="w3-bar w3-dark-gray">
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'home' %}">Accueil</a></div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'zone_list' %}">Liste des Zones</a>
        </div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>

    </div>
{% endblock %}

{% block content %}
    <h2>
        {% if object %}
            Modifier {{ object }}
        {% else %}
            Créer une nouvelle zone
        {% endif %}
    </h2>

    {% load static %}
    <form method="post" enctype="multipart/form-data" class="model-form">
        {% csrf_token %}
        <table class="w3-table w3-bordered w3-white">
            {{ form.as_table }}
        </table>
        <div class="w3-margin-top">
            <input type="submit" value="Enregistrer" class="w3-button w3-theme-l1 w3-round">
            <a class="w3-button w3-border w3-round" href="javascript:history.back()">Annuler</a>
        </div>

    </form>
    <style>
        td > input {
            width: 100%;
            border: none;
            background-color: #f8f8ca;
        }
        td > select {
            width: 100%;
            height: 40px !important;
            padding: 2px 8px;
            border: none;
            background-color: #f8f8ca;
        }
    </style>
{% endblock %}

core/templates/core/zone/zone_list.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumbs %}
    <div class="w3-bar w3-dark-gray">
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'home' %}">Accueil</a></div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>
    </div>
{% endblock %}
{% block content %}
    <h2>Liste des zones</h2>
    <a href="{% url 'zone_create' %}" class="w3-button w3-theme-l1 w3-round">Nouveau</a>
    <table class="w3-table w3-bordered w3-margin-top w3-white">
        <thead>
        <th>ID</th>
        <th>État du planning</th>
        <th>Désignation</th>
        <th>Site</th>
        <th>Entreprise</th>
        <th>Actions</th>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr {% if object.plan_state == 1 %}class="w3-text-gray" {% endif %}>
                <td>{{ object.pk }}</td>
                <td>{{ object.get_plan_state_display }}</td>
                <td>{{ object.designation }}</td>
                <td>{{ object.site }}</td>
                <td>{{ object.site.enterprise }}</td>
                <td class="w3-padding-small">
                    <a href="{% url 'zone_detail' parent_pk=object.pk  day_index=6 %}"
                       class="w3-button w3-round w3-padding-small">
                        {% include 'components/_view_icon.html' with height=19 %}
                    </a>
                    <a href="{% url 'zone_update' pk=object.pk %}" class="w3-button w3-round w3-padding-small">
                        {% include 'components/_modify_icon.html' with height=19 %}
                    </a>
                    <a href="{% url 'zone_delete' pk=object.pk %}" class="w3-button w3-round w3-padding-small">
                        {% include 'components/_delete_icon.html' with height=19 %}
                    </a>

                    {% if object.plan_state == 1 %}
                        <a href="{% url 'zone_confirm' pk=object.pk %}"
                           class="w3-button w3-theme-l1 w3-small w3-round">Confirmer</a>
                    {% elif object.plan_state == 2 %}
                        <a href="{% url 'zone_reopen' pk=object.pk %}"
                           class="w3-button w3-light-gray w3-small w3-round">Réouvrir</a>
                    {% endif %}

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

core/templates/core/zone/zone_reopen_planning.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumbs %}
    <div class="w3-bar w3-dark-gray">
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'home' %}">Accueil</a></div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>
        <div class="w3-bar-item"><a class="no-text-decoration" href="{% url 'zone_list' %}">Liste des Zones</a>
        </div>
        <div class="w3-bar-item"><img src="{% static 'core/icons/next_icon_red.svg' %}" height="18"></div>

    </div>
{% endblock %}
{% block content %}
    <form method="POST" action="{% url 'zone_reopen' pk=object.pk %}">
        {% csrf_token %}
        <p class="w3-padding-16 w3-padding-top-24">Voulez-vous vraiment <b>{{ action_name }}</b> le planning de la zone <b>{{ object }}</b> ?
        </p>
        <input class="w3-button w3-theme-l1 w3-round" type="submit" value="{{ action_name }}"/>
        <a class="w3-button w3-border w3-round" href="javascript:history.back()">Annuler</a>
    </form>
{% endblock %}